# Note  : *** the batch_size should be [8, 16], the number of GPUs is 8, and the transform type is BaseSilTransform (64 x 64)!!! ***
data_cfg:
  dataset_name: FVG
  dataset_root: your training path for FVG 
  dataset_test_root: your testing path for FVG 
  dataset_partition: datasets/FVG/FVG_CCVID_include_session3.json
  num_workers: 1
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: FVG_CCVID_ALL


evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 40000
  save_name: GaitApp_Baseline
  eval_func: identification_all
  sampler:
    batch_shuffle: false
    batch_size: 8
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 720 # limit the number of sampled frames to prevent out of memory
  metric: euc # cos
  transform:
    - type: BaseSilTransform
      img_w: 64



loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet_original
  - loss_term_weight: 0.1
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax_original
    log_accuracy: true
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet_cross_cloth 
  - loss_term_weight: 0.1
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax_cross_cloth
    log_accuracy: true


model_cfg:
  model: GaitApp_Baseline
  backbone_cfg:
    in_channels: 1
    layers_cfg: # Layers configuration for automatically model construction
      - BC-64
      - BC-64
      - M
      - BC-128
      - BC-128
      - M
      - BC-256
      - BC-256
    type: Plain
  SeparateFCs:
    in_channels: 256
    out_channels: 256
    parts_num: 31
  SeparateBNNecks:
    class_num: 136
    in_channels: 256
    parts_num: 31
  bin_num:
    - 16
    - 8
    - 4
    - 2
    - 1
  Encoder:
    in_channels:
      - 1
      - 32
      - 64
      - 128
  Decoder:
    in_channels:
      - 128
      - 64
      - 32
      - 16
      - 8
      - 1

optimizer_cfg:
  lr: 0.1
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 10000
    - 20000
    - 30000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true # half_percesion float for memory reduction and speedup
  fix_BN: false
  log_iter: 100
  optimizer_reset: true
  scheduler_reset: true
  with_test: true
  restore_ckpt_strict: true
  restore_hint:
    - ../GaitApp_Generator/output/CASIA-B/GaitApp_Generator/GaitApp_Generator/checkpoints/Encoder-20000.pt
    - ../GaitApp_Generator/output/CASIA-B/GaitApp_Generator/GaitApp_Generator/checkpoints/Decoder-20000.pt
  save_iter: 10000
  save_name: GaitApp_Baseline
  sync_BN: true
  total_iter: 40000
  sampler:
    batch_shuffle: false
    batch_size:
      - 8 # TripletSampler, batch_size[0] indicates Number of Identity
      - 16 #                 batch_size[1] indicates Samples sequqnce for each Identity
    frames_num_fixed: 30 # fixed frames number for training
    frames_num_max: 50 # max frames number for unfixed training
    frames_num_min: 25 # min frames number for unfixed traing
    sample_type: fixed_unordered # fixed control input frames number, unordered for controlling order of input tensor; Other options: unfixed_ordered or all_ordered
    type: TripletSampler
  transform:
    - type: BaseSilTransform
      img_w: 64
