# Note  : *** the batch_size should be [8, 16], the number of GPUs is 8, and the transform type is BaseSilTransform (64 x 64)!!! ***
data_cfg:
  dataset_name: CASIA-B
  dataset_root: your path for CASIA-B 
  dataset_partition: datasets/CASIA-B/CASIA-B.json
  num_workers: 1
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: CASIA-B




evaluator_cfg:
  enable_float16: false 
  restore_ckpt_strict: true
  restore_hint: 80000
  save_name: GaitApp_GaitGL
  eval_func: identification_all

  sampler:
    batch_size: 8
    sample_type: all_ordered
    type: InferenceSampler
  metric: euc # cos
  transform:
    - type: BaseSilTransform
      img_w: 64

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet_original
  - loss_term_weight: 1.0
    scale: 1
    type: CrossEntropyLoss
    log_accuracy: true
    label_smooth: false
    log_prefix: softmax_original
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet_cross_cloth 
  - loss_term_weight: 1.0
    scale: 1
    type: CrossEntropyLoss
    log_accuracy: true
    label_smooth: false
    log_prefix: softmax_cross_cloth


model_cfg:
  model: GaitApp_GaitGL
  channels: [32, 64, 128]
  class_num: 73
  Encoder:
    in_channels:
      - 1
      - 32
      - 64
      - 128
  Decoder:
    in_channels:
      - 128
      - 64
      - 32
      - 16
      - 8
      - 1


optimizer_cfg:
  lr: 1.0e-4
  solver: Adam
  weight_decay: 5.0e-4

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 70000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true
  with_test: true
  log_iter: 100
  optimizer_reset: true
  scheduler_reset: true
  with_test: true
  restore_ckpt_strict: true
  restore_hint:
    - ../GaitApp_Generator/output/CASIA-B/GaitApp_Generator/GaitApp_Generator/checkpoints/Encoder-20000.pt
    - ../GaitApp_Generator/output/CASIA-B/GaitApp_Generator/GaitApp_Generator/checkpoints/Decoder-20000.pt
  save_iter: 10000
  save_name: GaitApp_GaitGL
  sync_BN: true
  total_iter: 80000
  sampler:
    batch_shuffle: false
    batch_size:
      - 8
      - 16
    frames_num_fixed: 30
    frames_skip_num: 0
    sample_type: fixed_ordered
    type: TripletSampler
  transform:
    - type: BaseSilTransform
      img_w: 64
