# Note  : *** the batch_size should be [8, 16], the number of GPUs is 8, and the transform type is BaseSilTransform (64 x 64)!!! ***
data_cfg:
  dataset_name: FVG
  dataset_root: your training path for FVG 
  dataset_test_root: your testing path for FVG 
  dataset_partition: datasets/FVG/FVG_CCVID_include_session3.json
  num_workers: 1
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: FVG_CCVID_ALL




evaluator_cfg:
  enable_float16: false
  restore_ckpt_strict: true
  restore_hint: 40000
  save_name: GaitApp_GaitSet
  eval_func: identification_all
  sampler:
    batch_shuffle: false
    batch_size: 16
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 720 # limit the number of sampled frames to prevent out of memory
  metric: euc # cos
  transform:
    - type: BaseSilTransform
      img_w: 64

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet_original
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet_cross_cloth 


model_cfg:
  model: GaitApp_GaitSet
  in_channels:
    - 1
    - 32
    - 64
    - 128
  SeparateFCs:
    in_channels: 128
    out_channels: 256
    parts_num: 62
  bin_num:
    - 16
    - 8
    - 4
    - 2
    - 1
  Encoder:
    in_channels:
      - 1
      - 32
      - 64
      - 128
  Decoder:
    in_channels:
      - 128
      - 64
      - 32
      - 16
      - 8
      - 1


optimizer_cfg:
  lr: 0.1
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 10000
    - 20000
    - 30000
  scheduler: MultiStepLR


trainer_cfg:
  enable_float16: true
  log_iter: 100
  optimizer_reset: true
  scheduler_reset: true
  with_test: true
  restore_ckpt_strict: true
  restore_hint:
    - ../GaitApp_Generator/output/CASIA-B/GaitApp_Generator/GaitApp_Generator/checkpoints/Encoder-20000.pt
    - ../GaitApp_Generator/output/CASIA-B/GaitApp_Generator/GaitApp_Generator/checkpoints/Decoder-20000.pt
  save_iter: 10000
  save_name: GaitApp_GaitSet
  sync_BN: false
  total_iter: 40000
  sampler:
    batch_shuffle: false
    batch_size:
      - 8
      - 16
    frames_num_fixed: 30
    frames_num_max: 50
    frames_num_min: 25
    sample_type: fixed_unordered
    type: TripletSampler
  transform:
    - type: BaseSilTransform
      img_w: 64
